main_app/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :plugins

  # Application root
  map.root :controller => 'hosts', :action => 'search'

  # Hosts
  map.connect '', :controller => "hosts", :action => "search"
  map.connect 'hosts/search.:format', :controller => 'hosts', :action => 'search'
  map.connect 'hosts/index.:format', :controller => 'hosts', :action => 'index'

  map.resources :roles
  map.resources :repositories
  
  # Authlogic routes
  map.login 'login', :controller => 'user_sessions', :action => 'new'  
  map.logout 'logout', :controller => 'user_sessions', :action => 'destroy'  
  
  # Authlogic routes - registration
  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  
  map.connect 'users/:action/:id', :controller => "users"
  map.connect 'account/:action/:id', :controller => "users"
end

main_app/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :repositories
  
  def to_s
    name
  end
end

main_app/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        flash[:notice] = 'Role was successfully created.'
        format.html { redirect_to(@role) }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        flash[:notice] = 'Role was successfully updated.'
        format.html { redirect_to(@role) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

main_app/app/helpers/roles_helper.rb
module RolesHelper
end

main_app/app/views/roles/_repositories.html.erb
<% for repository in Repository.find :all %>
  <div>
  	<%= check_box_tag "role[repository_ids][]", repository.id, @role.repositories.include?(repository)%>  
 	<%= h repository.name %>
	(
	<%= h repository.uri %>
	)
  </div>
<% end %>

main_app/app/views/roles/edit.html.erb
<% title "Edit Role" %>

<% form_for(@role) do |f| %>
  	<%= f.error_messages %>
	<table class="managementEditTable">
		<tr>
			<th>Name</th>
			<th>Repositories available for the user</th>
		</tr>	
    	<tr>
			<td><%= f.text_field :name %></td>
			<td><%= render :partial => "repositories" %></td>
		</tr>
	</table>	
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

main_app/app/views/roles/index.html.erb
<% title "Roles List" %>

<div class="innerInnerContent">
	<table class="managementListTable">
  		<tr>
		    <th>Name</th>
			<th class="last"></th>
		</tr>

		<% @roles.each do |role| %>
		<tr>
		    <td><%=h role.name %></td>
		    <td class="last">
				<%= link_to 'Show', role %>
				<%= link_to 'Edit', edit_role_path(role) %>
				<%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %>
			</td>
		 </tr>
		<% end %>
	</table>
</div>
<br />

<%= link_to 'New role', new_role_path %>

main_app/app/views/roles/new.html.erb
<% title "New Role" %>

<% form_for(@role) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <%= render :partial => "repositories" %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', roles_path %>

main_app/app/views/roles/show.html.erb
<p>
  <b>Name:</b>
  <%=h @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>